// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa7HGjxnnqTBxxe58skUD5QCUK-fxVD1M',
    appId: '1:744551342723:web:e7cf2e4577fd7e1e5fb1b6',
    messagingSenderId: '744551342723',
    projectId: 'ponto-simples',
    authDomain: 'ponto-simples.firebaseapp.com',
    databaseURL: 'https://ponto-simples-default-rtdb.firebaseio.com',
    storageBucket: 'ponto-simples.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7XUhbr7hJlFhEqfrlF0qGOZBFsPlIcrw',
    appId: '1:744551342723:android:903191db189b76925fb1b6',
    messagingSenderId: '744551342723',
    projectId: 'ponto-simples',
    databaseURL: 'https://ponto-simples-default-rtdb.firebaseio.com',
    storageBucket: 'ponto-simples.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwou17yw41egzspeS8yPJztEojnvyccG8',
    appId: '1:744551342723:ios:b2f9431eaa66ca715fb1b6',
    messagingSenderId: '744551342723',
    projectId: 'ponto-simples',
    databaseURL: 'https://ponto-simples-default-rtdb.firebaseio.com',
    storageBucket: 'ponto-simples.appspot.com',
    iosBundleId: 'com.example.pi2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwou17yw41egzspeS8yPJztEojnvyccG8',
    appId: '1:744551342723:ios:b2f9431eaa66ca715fb1b6',
    messagingSenderId: '744551342723',
    projectId: 'ponto-simples',
    databaseURL: 'https://ponto-simples-default-rtdb.firebaseio.com',
    storageBucket: 'ponto-simples.appspot.com',
    iosBundleId: 'com.example.pi2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDa7HGjxnnqTBxxe58skUD5QCUK-fxVD1M',
    appId: '1:744551342723:web:6a659905fe1129b65fb1b6',
    messagingSenderId: '744551342723',
    projectId: 'ponto-simples',
    authDomain: 'ponto-simples.firebaseapp.com',
    databaseURL: 'https://ponto-simples-default-rtdb.firebaseio.com',
    storageBucket: 'ponto-simples.appspot.com',
  );
}
